name: Deploy Lambdas

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy createOrder
        run: |
          cd lambdas
          zip -r cmtr_aadapw7c_lambda_createOrder.zip cmtr_aadapw7c_lambda_createOrder
          aws lambda update-function-code \
            --function-name cmtr_aadapw7c_lambda_createOrder \
            --zip-file fileb://cmtr_aadapw7c_lambda_createOrder.zip

      - name: Deploy reserveStock
        run: |
          cd lambdas
          zip -r cmtr_aadapw7c_lambda_reserveStock.zip cmtr_aadapw7c_lambda_reserveStock
          aws lambda update-function-code \
            --function-name cmtr_aadapw7c_lambda_reserveStock \
            --zip-file fileb://cmtr_aadapw7c_lambda_reserveStock.zip

      - name: Deploy sendNotification
        run: |
          cd lambdas
          zip -r cmtr_aadapw7c_lambda_sendNotification.zip cmtr_aadapw7c_lambda_sendNotification
          aws lambda update-function-code \
            --function-name cmtr_aadapw7c_lambda_sendNotification \
            --zip-file fileb://cmtr_aadapw7c_lambda_sendNotification.zip
```

**Option B: GitLab CI**
Create a file named `.gitlab-ci.yml`:
```
image:
  name: amazon/aws-cli:2.33.20
  entrypoint: [""]

stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: "$AWS_REGION"

deploy_lambdas:
  stage: deploy
  only:
    - main
  before_script:
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - export AWS_DEFAULT_REGION="$AWS_REGION"

  script:
    - echo "Deploying Lambda functions..."
    - cd lambdas
    - zip -r cmtr_aadapw7c_lambda_createOrder.zip cmtr_aadapw7c_lambda_createOrder
    - aws lambda update-function-code --function-name cmtr_aadapw7c_lambda_createOrder --zip-file fileb://cmtr_aadapw7c_lambda_createOrder.zip

    - zip -r cmtr_aadapw7c_lambda_reserveStock.zip cmtr_aadapw7c_lambda_reserveStock
    - aws lambda update-function-code --function-name cmtr_aadapw7c_lambda_reserveStock --zip-file fileb://cmtr_aadapw7c_lambda_reserveStock.zip

    - zip -r cmtr_aadapw7c_lambda_sendNotification.zip cmtr_aadapw7c_lambda_sendNotification
    - aws lambda update-function-code --function-name cmtr_aadapw7c_lambda_sendNotification --zip-file fileb://cmtr_aadapw7c_lambda_sendNotification.zip
